// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectWilson.Server.Data;

#nullable disable

namespace ProjectWilson.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230519154300_EditionSeeding")]
    partial class EditionSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EditionProduct", b =>
                {
                    b.Property<int>("EditionsId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("EditionsId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("EditionProduct");

                    b.HasData(
                        new
                        {
                            EditionsId = 1,
                            ProductsId = 1
                        },
                        new
                        {
                            EditionsId = 2,
                            ProductsId = 1
                        },
                        new
                        {
                            EditionsId = 3,
                            ProductsId = 1
                        },
                        new
                        {
                            EditionsId = 4,
                            ProductsId = 2
                        },
                        new
                        {
                            EditionsId = 5,
                            ProductsId = 2
                        },
                        new
                        {
                            EditionsId = 6,
                            ProductsId = 2
                        },
                        new
                        {
                            EditionsId = 4,
                            ProductsId = 3
                        },
                        new
                        {
                            EditionsId = 5,
                            ProductsId = 3
                        },
                        new
                        {
                            EditionsId = 6,
                            ProductsId = 3
                        },
                        new
                        {
                            EditionsId = 7,
                            ProductsId = 5
                        },
                        new
                        {
                            EditionsId = 8,
                            ProductsId = 5
                        });
                });

            modelBuilder.Entity("ProjectWilson.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "book",
                            Name = "Books",
                            Url = "books"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "camera-slr",
                            Name = "Electronics",
                            Url = "electronics"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "aperture",
                            Name = "Video Games",
                            Url = "video-games"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "musical-note",
                            Name = "Music",
                            Url = "music"
                        });
                });

            modelBuilder.Entity("ProjectWilson.Shared.Edition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Editions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Paperback"
                        },
                        new
                        {
                            Id = 2,
                            Name = "E-Book"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Audiobook"
                        },
                        new
                        {
                            Id = 4,
                            Name = "PC"
                        },
                        new
                        {
                            Id = 5,
                            Name = "PlayStation"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Xbox"
                        },
                        new
                        {
                            Id = 7,
                            Name = "iPhone Pro"
                        },
                        new
                        {
                            Id = 8,
                            Name = "iPhone Pro Max"
                        });
                });

            modelBuilder.Entity("ProjectWilson.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            DateCreated = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a very intuitive description of the book !",
                            Image = "https://upload.wikimedia.org/wikipedia/en/b/bd/H2G2_UK_front_cover.jpg",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 19.99m,
                            Price = 9.99m,
                            Title = "The Hitchhiker's Guide to the Galaxy"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            DateCreated = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a very intuitive description of the game !",
                            Image = "https://upload.wikimedia.org/wikipedia/en/2/25/Half-Life_2_cover.jpg",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 29.99m,
                            Price = 8.19m,
                            Title = "Half-Life 2"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            DateCreated = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is a very intuitive description of the game !",
                            Image = "https://upload.wikimedia.org/wikipedia/en/a/a5/Grand_Theft_Auto_V.png",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 29.99m,
                            Price = 49.99m,
                            Title = "Grand Theft Auto 5"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            DateCreated = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Song performed by Noa Kirel during Eurovision 2023 representing Israel",
                            Image = "https://upload.wikimedia.org/wikipedia/en/thumb/b/bf/Unicorn_%28song%29.jpeg/220px-Unicorn_%28song%29.jpeg",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 0.00m,
                            Price = 9.99m,
                            Title = "Unicorn - Noa Kirel"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            DateCreated = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The newest iPhone by Apple",
                            Image = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/IPhone_14_Pro_vector.svg/220px-IPhone_14_Pro_vector.svg.png",
                            IsDeleted = false,
                            IsPublic = false,
                            OriginalPrice = 1200.99m,
                            Price = 700.00m,
                            Title = "iPhone 14 Pro"
                        });
                });

            modelBuilder.Entity("EditionProduct", b =>
                {
                    b.HasOne("ProjectWilson.Shared.Edition", null)
                        .WithMany()
                        .HasForeignKey("EditionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectWilson.Shared.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectWilson.Shared.Product", b =>
                {
                    b.HasOne("ProjectWilson.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
